# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_imageuploadform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUploadForm',
        ),
    ]
